services:
  # ============== DATABASES ==============
#  task-db:
#    image: postgres:15
#    container_name: sapphire-task-db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: task_db
#    ports:
#      - "5432:5432"
#    volumes:
#      - task-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - sapphire-network
#    restart: unless-stopped

  preprocessing-db:
    image: postgres:15
    container_name: sapphire-preprocessing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: preprocessing_db
    ports:
      - "5433:5432"
    volumes:
      - preprocessing-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sapphire-network
    restart: unless-stopped

  postprocessing-db:
    image: postgres:15
    container_name: sapphire-postprocessing-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postprocessing_db
    ports:
      - "5434:5432"
    volumes:
      - postprocessing-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sapphire-network
    restart: unless-stopped

  user-db:
    image: postgres:15
    container_name: sapphire-user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5435:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sapphire-network
    restart: unless-stopped

  # ============== SERVICES ==============
  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    container_name: sapphire-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - preprocessing-api
      - postprocessing-api
      - user-api
    networks:
      - sapphire-network
    restart: unless-stopped
    # For development: mount code as volume
    volumes:
      - ./services/api-gateway:/code

#  task-api:
#    build:
#      context: .
#      dockerfile: ./services/task-service/Dockerfile
#    container_name: sapphire-task-api
#    ports:
#      - "8001:8001"
#    depends_on:
#      task-db:
#        condition: service_healthy
#    environment:
#      DATABASE_URL: postgresql://postgres:password@task-db:5432/task_db
#      TEST_DATABASE_URL: postgresql://postgres:password@task-db:5432/task_db_test
#      PYTHONPATH: /code
#      LOG_LEVEL: INFO
#    networks:
#      - sapphire-network
#    restart: unless-stopped
#    # For development: mount code as volume
#    volumes:
#      - ./services/task-service:/code

  preprocessing-api:
    build:
      context: .
      dockerfile: ./services/preprocessing/Dockerfile
    container_name: sapphire-preprocessing-api
    ports:
      - "8002:8002"
    depends_on:
      preprocessing-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@preprocessing-db:5432/preprocessing_db
#      TEST_DATABASE_URL: postgresql://postgres:password@db:5432/preprocessing_db_test
      PYTHONPATH: /code
      LOG_LEVEL: INFO
    networks:
      - sapphire-network
    restart: unless-stopped
    # For development: mount code as volume
    volumes:
      - ./services/preprocessing:/code
      - /Users/maxat/data/kyg_data_forecast_tools/intermediate_data:/intermediate_data

  postprocessing-api:
    build:
      context: .
      dockerfile: ./services/postprocessing/Dockerfile
    container_name: sapphire-postprocessing-api
    ports:
      - "8003:8003"
    depends_on:
      postprocessing-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@postprocessing-db:5432/postprocessing_db
#      TEST_DATABASE_URL: postgresql://postgres:password@db:5432/postprocessing_db_test
      PYTHONPATH: /code
      LOG_LEVEL: INFO
    networks:
      - sapphire-network
    restart: unless-stopped
    # For development: mount code as volume
    volumes:
      - ./services/postprocessing:/code
      - /Users/maxat/data/kyg_data_forecast_tools/intermediate_data:/intermediate_data

  user-api:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    container_name: sapphire-user-api
    ports:
      - "8004:8004"
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - sapphire-network
    restart: unless-stopped
    volumes:
      - ./services/user:/code

volumes:
  task-data:
  preprocessing-data:
  postprocessing-data:
  user-data:

networks:
  sapphire-network:
    driver: bridge
